* typin'
** TODO

** Ideas
- Levels? Start super easy, get out... get's harder. Maybe not "levels", but rooms, so there is a progression - very easy to teach mechanics.
  
- only need to type ~4 characters then the word autocompletes?... and/or, like a combo: type whole words and get "on fire" and it starts autocompleting, and you zoom faster. Should feel like a typing GOD.

  (remember power-up mode in Sublime/Atom?)
  
- later skill: words are related to other nearby words, highlihted and can start typing them to teleport
- Gain a supply of "forward-word/ backward word/ sentence etc" shortcuts. Emacs/vim binds as powerups.

  ** Other  PRototyep:
  - might work better as a dungeon crawler than a platformer... but how does the typing work if you are, say, in a corridor:
this is the level
a    x
boop of the thing
... maybe like, top down and the words are paths, can choose the forks

- mash-mode powerup (just mash any keys to progress),

  - letters fall away, platforms fall down (must type faster)
  - gumbas change the letters as youre typing: mix up the words.

  - More "flow-y"... always moving to right - can go up and down, but not really backwards.
    (maybe if level disintegrates behind you)
    - should build momentum: combo goes faster, level has chutes and portals to make it feel less "only-go-right",
      they propell you forward
 

*** Dum rando
- tying rhythm game section.
- typing of the dead section.
- flappy bird typing tutor section
- marquee text as moving platforms

** aesthetic
https://www.gridsagegames.com/rexpaint/gallery.html

- or, could be bookish style. Old parchment vibe with ANSI gfx on top

