export const txt = `


was so odd a mixture of quick parts, sarcastic humour, reserve, and caprice, that the experience of three-and-twenty years had been insufficient to{5} make his wife understand his character. Her mind was less diffic.lt to develope. She was a woman of mean understanding, little information, and uncertain temper.
                                                        u                           a                                      l                              f                       h
                                                        p                           n                                      o                              u                       i
An invitation to dinner was soon afterwards despatched; and already had Mrs. Bennet planned the courses that were to do credit to her housekeeping, when an answer arrived which deferred it all. Mr. Bingley was obliged to be in town the following day, and consequently unable to accept the honour of their invitation, etc.
     i                  i                                       n                                  u                                  h                                           h
     s                  n                                       i                                  p                                  u                                           i
When she was discontented, she fancied herself nervous. The business of her life was to get her daughters married: its solace was visiting and news. Indeed, sir, I have not the least intention of dancing. I entreat you not to suppose that I moved this way in order to beg for a partner.
                   u                   t                                    o                                          a                       h                                  h                   p
                   p                   o                                    f                                          n                       u                                  i                   o
it's not    Elizabeth                  ecting that she was herself becoming an object of some interest in the eyes of his friend. Mr. Darcy had at first scarcely allowed her to be pretty: he had looked at her without admiration at the ball; and when they next met, he looked at her only to criticise.
       u             g                                 y                                  n              o                             a                 f                        h
       p             o                                 o                                  m              l                             n                 u                        i
beyond the recesses of                            How long has she been such a favourite? and pray when am I to wish you joy? which a pair of fine eyes in the face of a pretty woman can bestow. they repaired to her room on leaving the dining-parlour, and sat with her till summoned to coffee. She was still very poorly,


was so odd a mixture of quick parts,                   reserve, and caprice, that the                                years had been insufficient to{5} make his wife understand his character. Her mind was less diffic.lt to develope. She was a woman of mean understanding, little information, and uncertain temper.
                                                        u                           a                                      l                              f                       h
                                                        p                           n                                      o                              u                       i
An invitation to dinner was soon afterwards despatched; and already had Mrs. Bennet planned the courses that were to do credit to her housekeeping, when an answer arrived which deferred it all. Mr. Bingley was obliged to be in town the following day, and consequently unable to accept the honour of their invitation, etc.
     i                  i                                       n                                  u                                  h                                           h
     s                  n                                       i                                  p                                  u                                           i
When she was discontented, she fancied herself nervous. The business of her I        to get her daughters married: its solace was visiting and news. Indeed, sir, I have not the least intention of dancing. I entreat you not to suppose that I moved this way in order to beg for a partner.
                   u                   t                                    o                                          a                       h                                  h                   p
                   p                   o                                    f                                          n                       u                                  i                   o
it's not    Elizabeth was far from suspecting that she was herself becoming an object of some interest in             his friend. Mr. Darcy had at first scarcely allowed her to be pretty: he had looked at her without admiration at the ball; and when they next met, he looked at her only to criticise.
       u             g                                 y                                  n              o                             a                 f                        h
       p             u                                 o                                  m              l                             n                 u                        i
beyond the recesses of                            How long has she been such a favourite? and pray when am I to                     a pair of fine eyes in the face of a pretty woman can bestow. they repaired to her room on leaving the dining-parlour, and sat with her till summoned to coffee. She was still very poorly,


was so odd a mixture of quick parts, sarcastic humour, reserve, and caprice, that the experience of three-and-twenty years had                         make his wife understand his character. Her mind was less diffic.lt to develope. She was a woman of mean understanding, little information, and uncertain temper.
                                                        u                           a                                      l                              f                       h
                                                        p                           n                                      o                              u                       i
An invitation to dinner was soon afterwards             and already had Mrs. Bennet planned the courses that were to do credit to her housekeeping, when an answer arrived which deferred it all. Mr. Bingley was obliged to be in town the following day, and consequently unable to accept the honour of their invitation, etc.
     i                  i                                       n                                  u                                  h                                           h
     s                  n                                       i                                  p                                  u                                           i
When she was discontented, she fancied herself nervous.         ness of her life was to get her daughters married: its solace was visiting and news. Indeed, sir, I have not the least intention of dancing. I entreat you not to suppose that I moved this way in order to beg for a partner.
                   u                   t                                    o                                          a                       h                                  h                   p
                   p                   o                                    f                                          n                       u                                  i                   o
it's not    Elizabeth was far from suspecting that she was herself becoming an object of some interest in the eyes of his friend. Mr. Darcy had at first scarcely allowed her to be pretty: he had looked at her without admiration at the ball; and when they next met, he looked at her only to criticise.
       u             g                                 y                                  n              o                             a                 f                        h
       p             o                                 o                                  m              l                             n                 u                        i
beyond the recesses of the I am all astonishment. How long has she been such a favourite? and pray when am I to wish you joy? which a pair of fine eyes in the face of a pretty woman can bestow. they repaired to her room on leaving the dining-parlour, and sat with her till summoned to coffee. She was still very poorly,
                                     o                                   o
                                     g                                   p
was so odd a mixture of quick parts, sarcastic humour, reserve, and caprice, that the experience of                  years had been insufficient to{5} make his wife understand his character. Her mind was less diffic.lt to develope. She was a woman of mean understanding, little information, and uncertain temper.
                        o                               u                           a                                      l                              f                       h
                        g                               p                           n                                      o                              u                       i
An invitation to dinner was soon afterwards despatched; and already had Mrs. Bennet planned the courses                 credit to her housekeeping,       n                which deferred it all. Mr. Bingley was obliged to be in town the following day, and consequently unable to accept the honour of their invitation, etc.
     i                  i                                       n                                  u                                  h                   r                       h
     s                  n                                       i                                  p                                  u                   u                       i
When she was discontented, she fancied herself.         The business of her life was to get her daughters married: its solace was visiting and news.      d                      least intention of dancing. I entreat you not to suppose that I moved this way in order to beg for a partner.
                   u                   t                                    o                                          a                       h          r                       h                   p
                   p                   o                                    f                                          n                       u          u                       i                   o
it's not    Elizabeth was far from suspecting          was herself becoming an object of some interest in the eyes of his friend. Mr. Darcy had at first scarcely allowed her to be pretty: he had looked at her without admiration at the ball; and when they next met, he looked at her only to criticise. boop boop.
       u             g                                 y                                  n              o                             a                 f                        h
       p             o                                 o                                  m              l                             n                 u                        i
beyond the recesses of the I am all astonishment. How long has she been such a favourite? and pray when am I to wish you joy? which a pair              in the face of a pretty woman can bestow.                                          dining-parlour, and sat with her till summoned to coffee. She was still very poorly,
                                      d                                                                                                                                            h
                                      g                                                                                                                                            i
was so odd a mixture of quick parts, sarcastic humour, reserve, and caprice, that the experience                           had been insufficient to{5} make his wife understand mis character. Her mind was less diffic.lt to develope. She was a woman of mean understanding, little information, and uncertain temper.
                                                        u                           a                                      l                                                      h
                                                        p                           n                                      o                                                      i
An invitation to dinner was soon afterwards despatched; and already had Mrs. Bennet planned the courses                 credit to her a                                          defer            Mr. Bingley was obliged to be in town the following day, and consequently unable to accept the honour of their invitation, etc.
     i                  i                                       n                                  u                                  h                                           h
     s                  n                                       i                                  p                                  u                                           i
When she was discontented, she fancied herself nervous. The business of her life was to get her daughters married: its solace was visiting and news. Indeed, sir, I have not the least              dancing. I entreat you not to suppose that I moved this way in order to beg for a partner.
                   u                   t                                    o                                          a                       h                                  h                   p
                   p                   o                                    f                                          n                       u                                  i                   o
it's not    Elizabeth was far from suspecting that she was herself becoming an object of some interest in the eyes of his friend. Mr. Darcy had at first scarcely allowed her to be pretty: he had looked at her without admiration at the ball; and when they next met, he looked at her only to criticise.
       u             g                                 y                                  n              o                             a                 f                        h
       p             o                                 o                                  m              l                             n                 u                        i
beyond the recesses of the I am all astonishment. How long has she been such a favourite? and pray when am I to wish you joy? which a pair of fine eyes in the face of a pretty woman can bestow. they repaired to her room on leaving the dining-parlour, and sat with her till summoned to coffee. She was still very poorly,
                                    g                                   o
                                    a                                   p
was so odd a mixture of quick parts, sarcastic humour, reserve, and caprice, that the experience of three-and-twenty years had been insufficient to{5} make his wife understand his character. Her mind was less diffic.lt to develope. She was a woman of mean understanding, little information, and uncertain temper.
                                                        u                           a                                      l                              f                       h
                                                        p                           n                                      o                              u                       i
An invitation to dinner was soon afterwards despatched; and already had Mrs. Bennet planned the courses that were to do credit to her housekeeping, when an answer arrived which deferred it all. Mr. Bingley was obliged to be in town the following day, and consequently unable to accept the honour of their invitation, etc.
     i                  i                                       n                                  u                                  h                                           h
     s                  n                                       i                                  p                                  u                                           i
When she was discontented, she fancied herself nervous. The business of her life was to get her daughters married: its solace was visiting and news. Indeed, sir, I have not the least intention of dancing. I entreat you not to suppose that I moved this way in order to beg for a partner.
                   u                   t                                    o                                          a                       h                                  h                   p
                   p                   o                                    f                                          n                       u                                  i                   o
it's not    Elizabeth was far from suspecting that she was herself becoming an object of some interest in the eyes of his friend. Mr. Darcy had at first scarcely allowed her to be pretty: he had looked at her without admiration at the ball; and when they next met, he looked at her only to criticise.
       u             g                                 y                                  n              o                             a                 f                        h
       p             o                                 o                                  m              l                             n                 u                        i
beyond the recesses of the I am all astonishment. How long has she been such a favourite? and pray when am I to wish you joy? which a pair of fine eyes in the face of a pretty woman can bestow. they repaired to her room on leaving the dining-parlour, and sat with her till summoned to coffee. She was still very poorly,

`;
